# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Check GitHub Actions
  # Workflow files stored in the default location of `.github/workflows`

  # Root.

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"

  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  # Languages.

  - directory: "/by-dataframe/dask"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/by-dataframe/pandas"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/by-language/csharp-efcore"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"

  - directory: "/by-language/csharp-npgsql"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"

  - directory: "/by-language/elixir-postgrex"
    package-ecosystem: "mix"
    schedule:
      interval: "daily"

  - directory: "/by-language/go-pgx"
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"

  - directory: "/by-language/java-jdbc"
    package-ecosystem: "maven"
    schedule:
      interval: "daily"

  - directory: "/by-language/java-jooq"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"

  - directory: "/by-language/java-qa"
    package-ecosystem: "maven"
    schedule:
      interval: "daily"

  - directory: "/by-language/php-amphp"
    package-ecosystem: "composer"
    schedule:
      interval: "daily"

  - directory: "/by-language/php-pdo"
    package-ecosystem: "composer"
    schedule:
      interval: "daily"

  - directory: "/by-language/python-connectorx"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/by-language/python-dbapi"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/by-language/python-sqlalchemy"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/by-language/python-turbodbc"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/by-language/ruby"
    package-ecosystem: "bundler"
    schedule:
      interval: "daily"

  - directory: "/by-language/rust-postgres"
    package-ecosystem: "cargo"
    schedule:
      interval: "daily"

  # Applications.

  - directory: "/application/apache-superset"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/application/cratedb-toolkit"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/application/metabase"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/application/metabase"
    package-ecosystem: "docker-compose"
    schedule:
      interval: "daily"

  - directory: "/application/records"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  # Frameworks.

  - directory: "/framework/dbt/basic"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/framework/dbt/materialize"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/framework/flink/kafka-jdbcsink-java"
    package-ecosystem: "docker-compose"
    schedule:
      interval: "daily"

  - directory: "/framework/gradio"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/framework/mcp"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/framework/records"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/framework/streamlit"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  # Operation.

  - directory: "/operation/compose/ssl"
    package-ecosystem: "docker-compose"
    schedule:
      interval: "daily"

  # Topics.

  - directory: "/topic/machine-learning/automl"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/topic/machine-learning/llm-langchain"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/topic/machine-learning/llama-index"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/topic/machine-learning/mlops-mlflow"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/topic/timeseries"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  # Testing.

  - directory: "/testing/testcontainers/java"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"

  - directory: "/testing/native/python-pytest"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/testing/native/python-unittest"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/testing/testcontainers/python-pytest"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"

  - directory: "/testing/testcontainers/python-unittest"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
