# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Check GitHub Actions
  # Workflow files stored in the default location of `.github/workflows`

  # Root.

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"

  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  # Languages.

  - directory: "/by-language/csharp-npgsql"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"

  - directory: "/by-language/java-jdbc"
    package-ecosystem: "maven"
    schedule:
      interval: "weekly"

  - directory: "/by-language/java-jooq"
    package-ecosystem: "gradle"
    schedule:
      interval: "weekly"

  - directory: "/by-language/java-qa"
    package-ecosystem: "maven"
    schedule:
      interval: "weekly"

  - directory: "/by-language/php-amphp"
    package-ecosystem: "composer"
    schedule:
      interval: "weekly"

  - directory: "/by-language/php-pdo"
    package-ecosystem: "composer"
    schedule:
      interval: "weekly"

  - directory: "/by-language/python-sqlalchemy"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  - directory: "/by-language/ruby"
    package-ecosystem: "bundler"
    schedule:
      interval: "weekly"

  # Topics.

  - directory: "/topic/machine-learning/automl"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  - directory: "/topic/machine-learning/llm-langchain"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  - directory: "/topic/machine-learning/mlops-mlflow"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  # Testing.

  - directory: "/testing/testcontainers/java"
    package-ecosystem: "gradle"
    schedule:
      interval: "weekly"
