# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Check GitHub Actions
  # Workflow files stored in the default location of `.github/workflows`
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"


  # Check individual projects in subfolders.

  - directory: "/by-language/csharp-npgsql" # Location of package manifests
    package-ecosystem: "nuget" # See documentation for possible values
    schedule:
      interval: "monthly"

  - directory: "/by-language/java-jdbc"
    package-ecosystem: "maven"
    schedule:
      interval: "monthly"

  - directory: "/by-language/java-jooq"
    package-ecosystem: "gradle"
    schedule:
      interval: "monthly"

  - directory: "/by-language/php-amphp"
    package-ecosystem: "composer"
    schedule:
      interval: "monthly"

  - directory: "/by-language/php-pdo"
    package-ecosystem: "composer"
    schedule:
      interval: "monthly"

  - directory: "/by-language/python-sqlalchemy"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"

  - directory: "/by-language/ruby"
    package-ecosystem: "bundler"
    schedule:
      interval: "monthly"

  - directory: "/testing/testcontainers/java"
    package-ecosystem: "gradle"
    schedule:
      interval: "monthly"
