[destination.cratedb.credentials]
# CrateDB PostgreSQL interface
host = "localhost"
port = 5432
username = "crate"
password = ""

[destination.sqlalchemy.credentials]
# CrateDB HTTP interface
# https://dlthub.com/docs/dlt-ecosystem/destinations/sqlalchemy
drivername = "crate"
host = "localhost"
port = 4200
database = ""
username = "crate"
password = ""

[sources.sql_database.credentials]
# CrateDB HTTP interface
# https://dlthub.com/docs/dlt-ecosystem/verified-sources/sql_database/setup
drivername = "crate"
host = "localhost"
port = 4200
database = ""
username = "crate"
password = ""
