services:

  # CrateDB database.
  cratedb:
    image: docker.io/crate/crate:${CRATEDB_VERSION:-latest}
    command: >
      crate
        '-Cdiscovery.type=single-node'
        '-Cstats.enabled=true'
    ports:
      - "4200:4200"
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4200"]
      start_period: 3s
      interval: 1.5s
      retries: 30
      timeout: 30s

  # RustFS storage.
  rustfs:
    image: docker.io/rustfs/rustfs:1.0.0-beta.1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ADDRESS: "0.0.0.0:9000"
      RUSTFS_SERVER_DOMAINS: "rustfs"
      RUSTFS_ACCESS_KEY: "accesskey"
      RUSTFS_SECRET_KEY: "secretkey"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://rustfs:9000/health"]
      start_period: 3s
      interval: 1.5s
      retries: 30
      timeout: 30s

  # Initialize RustFS: Create test buckets using mc client.
  rustfs-init:
    image: docker.io/rustfs/rc:latest
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/rc alias set rustfs http://rustfs:9000 accesskey secretkey) do echo '...waiting...' && sleep 1; done;
      /usr/bin/rc mb rustfs/testdrive;
      echo 'RustFS initialization complete';
      tail -f /dev/null
      "

  # Airflow scheduler.
  scheduler:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      AIRFLOW__CORE__TEST_CONNECTION: "Enabled"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW_CONN_CRATEDB_CONNECTION: "postgresql://crate:crate@cratedb:5432/doc?sslmode=disable"
      CRATEDB_SQLALCHEMY_URL: "crate://crate:crate@cratedb:4200"
    depends_on:
      cratedb:
        condition: service_healthy
      rustfs:
        condition: service_healthy
      rustfs-init:
        condition: service_started
