# Streamlit secrets file for CrateDB on localhost.
# https://docs.streamlit.io/develop/api-reference/connections/secrets.toml
# .streamlit/secrets.toml

[connections.cratedb]
dialect = "crate"
host = "localhost"
port = "4200"
username = "crate"
password = ""
