# Streamlit secrets file for CrateDB Cloud.
# https://docs.streamlit.io/develop/api-reference/connections/secrets.toml
# .streamlit/secrets.toml

[connections.cratedb]
dialect = "crate"
host = "example.gke1.us-central1.gcp.cratedb.net"
port = "4200"
username = "admin"
password = "g_,8.F0fNbVSk0.*!n54S5c,"

[connections.cratedb.create_engine_kwargs.connect_args]
ssl = true
