[tool.pytest.ini_options]
minversion = "2.0"
addopts = """
  -rfEX -p pytester --strict-markers --verbosity=3 --capture=no
  """
# --cov=. --cov-report=term-missing --cov-report=xml
env = [
    "CRATEDB_CONNECTION_STRING=crate://crate@localhost/?schema=testdrive",
    "PYDEVD_DISABLE_FILE_VALIDATION=1",
]

#log_level = "DEBUG"
#log_cli_level = "DEBUG"

testpaths = [
    "*.py",
]
xfail_strict = true
markers = [
]

# pytest-notebook settings
nb_test_files = true
nb_coverage = true
nb_diff_replace = [
    # Compensate output of `crash`.
    '"/cells/*/outputs/*/text" "\(\d.\d+ sec\)" "(0.000 sec)"',
]
# `vector_search.py` does not include any output(s).
nb_diff_ignore = [
    "/metadata/language_info",
    "/cells/*/execution_count",
    "/cells/*/outputs/*/execution_count",

    # Do not compare details of cell outputs.
    # It is impossible to maintain efficiently.
    "/cells/*/outputs",
]

[tool.coverage.run]
branch = false

[tool.coverage.report]
fail_under = 0
show_missing = true
omit = [
    "conftest.py",
    "test*.py",
]
