{
 "title": "Weather data",
 "time": { "from": "2023-04-05T06:00:20.000Z", "to": "2023-04-27T06:45:14.000Z" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(timestamp) AS \"Measurements\",\n  COUNT(DISTINCT location) AS \"Cities\"\nFROM demo.weather_data\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nMIN(timestamp) \"First Measurement\",\nMAX(timestamp) \"Last Measurement\"\nFROM demo.weather_data;"
    }
   ]
  },
  {
   "title": "Highest temperature by city",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT location,\n    max(temperature) AS highest_temp,\n    max_by(timestamp, temperature) AS time_of_highest_temp\nFROM demo.weather_data\nGROUP BY location;"
    }
   ]
  },
  {
   "title": "Temperature vs Interpolated Temperature in Berlin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH OrderedData AS (\n    SELECT timestamp,\n           location,\n           temperature,\n           LAG(temperature, 1) IGNORE NULLS OVER w AS prev_temp,\n           LEAD(temperature, 1) IGNORE NULLS OVER w AS next_temp\n    FROM demo.weather_data\n    WINDOW w AS (PARTITION BY location ORDER BY timestamp)\n)\nSELECT timestamp,\n       location,\n       COALESCE(temperature, (prev_temp + next_temp)/2) AS interpolated_temperature,\n       temperature AS temperature\nFROM OrderedData\nWHERE location='Berlin'\nORDER BY timestamp,location;"
    }
   ]
  },
  {
   "title": "Moving Averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp, \n    location,\n    temperature,\n    AVG(temperature) OVER w_10 AS temperature_ma_10,\n    AVG(temperature) OVER w_20 AS temperature_ma_20,\n    humidity,\n    AVG(humidity) OVER w_10 AS humidity_ma_10,\n    AVG(humidity) OVER w_20 AS humidity_ma_20,\n    wind_speed,\n    AVG(wind_speed) OVER w_10 AS wind_speed_ma_10,\n    AVG(wind_speed) OVER w_20 AS wind_speed_ma_20\nFROM \n    demo.weather_data\nWINDOW\n    w_10 AS (ORDER BY location, timestamp ROWS BETWEEN 10 PRECEDING AND CURRENT ROW),\n    w_20 AS (ORDER BY location, timestamp ROWS BETWEEN 20 PRECEDING AND CURRENT ROW)\n"
    }
   ]
  },
  {
   "title": "Weather data stations around Berlin",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT  city,\n    latitude(geopoint) AS latitude,\n    longitude(geopoint) AS longitude\nFROM demo.weather_stations\nWHERE distance('POINT(13.4050 52.5200)'::GEO_POINT, geopoint) < 1000000 \n"
    }
   ]
  }
 ]
}