[tool.pytest.ini_options]
minversion = "2.0"
addopts = """
  -rfEX -p pytester --strict-markers --verbosity=3
  """
# --cov=. --cov-report=term-missing --cov-report=xml
env = [
    "CRATEDB_CONNECTION_STRING=crate://crate@localhost/?ssl=false",
    "PYDEVD_DISABLE_FILE_VALIDATION=1",
]

#log_level = "DEBUG"
#log_cli_level = "DEBUG"

testpaths = [
    "*.py",
]
xfail_strict = true
markers = [
]

[tool.coverage.run]
branch = false

[tool.coverage.report]
fail_under = 0
show_missing = true
omit = [
    "conftest.py",
    "test*.py",
]
