databases:
  tutorial:
    db_host: postgresql
    db_port: 5432
    db_name: tutorial
    db_user: postgres
    db_password: postgres

    #create_table:
    #  regexp: /.+/
    #  method: create_table

    fields_jsonb_column: null
    tags_jsonb_column: null

    #field_columns:
    #  - value
    #  - field2
