[tool.pytest.ini_options]
minversion = "2.0"
addopts = """
  -rfEXs -p pytester --strict-markers --verbosity=3
  """
log_level = "DEBUG"
log_cli_level = "DEBUG"
testpaths = ["*.py"]
xfail_strict = true
markers = [
]
