name: Apache Superset

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/framework-apache-superset.yml'
    - 'framework/apache-superset/**'
    - 'requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/framework-apache-superset.yml'
    - 'framework/apache-superset/**'
    - 'requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        superset-version: [ "2.*", "3.*" ]
        python-version: [ "3.11" ]

    services:
      cratedb:
        image: crate/crate:nightly
        ports:
          - 4200:4200
          - 5432:5432
        env:
          CRATE_HEAP_SIZE: 4g

    name: Superset ${{ matrix.superset-version }}, Python ${{ matrix.python-version }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            requirements-test.txt

      - name: Install utilities
        run: |
          pip install -r requirements.txt

      - name: Install Apache Superset ${{ matrix.superset-version }}
        run: |
          pip install 'apache-superset==${{ matrix.superset-version }}'

      - name: Validate framework/apache-superset
        run: |
          ngr test --accept-no-venv framework/apache-superset
