name: "Apache Flink: Kafka to JDBC sink (Java)"

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/framework-flink-kafka-java.yml'
    - 'framework/flink/kafka-jdbcsink-java/**'
    - '/requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/framework-flink-kafka-java.yml'
    - 'framework/flink/kafka-jdbcsink-java/**'
    - '/requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]

    name: OS ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Validate framework/flink/kafka-jdbcsink-java
        run: |
          # TODO: Generalize invocation into `ngr` test runner.
          cd framework/flink/kafka-jdbcsink-java
          bash test.sh
