name: MCP

on:
  pull_request:
    paths:
    - '.github/workflows/framework-mcp.yml'
    - 'framework/mcp/**'
    - '/requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/framework-mcp.yml'
    - 'framework/mcp/**'
    - '/requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "
     Python: ${{ matrix.python-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.10', '3.13' ]
        cratedb-version: [ 'nightly' ]

    services:
      cratedb:
        image: crate/crate:${{ matrix.cratedb-version }}
        ports:
          - 4200:4200
          - 5432:5432
        env:
          CRATE_HEAP_SIZE: 4g

    env:
      UV_SYSTEM_PYTHON: true

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            framework/mcp/requirements*.txt

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install JBang
        uses: jbangdev/setup-jbang@main

      - name: Configure JBang
        run: |
          jbang trust add https://github.com/quarkiverse

      - name: Install utilities
        run: |
          uv pip install -r requirements.txt

      - name: Validate framework/mcp
        run: |
          ngr test --accept-no-venv framework/mcp
