name: "Compose: CrateDB with SSL"

on:
  pull_request:
    paths:
    - '.github/workflows/operation-compose-ssl.yml'
    - 'operation/compose/ssl/**'
    - '/requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/operation-compose-ssl.yml'
    - 'operation/compose/ssl/**'
    - '/requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "
     Python ${{ matrix.python-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.13'

    steps:

      - name: Acquire sources
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          python-version: ${{ matrix.python-version }}

      - name: Install utilities
        run: uv pip install --requirements=requirements.txt

      - name: Validate operation/compose/ssl
        run: |
          # TODO: Use `uv` for installing Apache Superset.
          # Hint: Currently does not work because directory includes Python files.
          #       https://github.com/pyveci/pueblo/issues/248
          cd operation/compose/ssl
          make test
