name: MLflow

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/test-mlflow.yml'
    - 'topic/machine-learning/mlops-mlflow/**'
    - 'requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/test-mlflow.yml'
    - 'topic/machine-learning/mlops-mlflow/**'
    - 'requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "
     Python: ${{ matrix.python-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.10' ]
        cratedb-version: [ 'nightly' ]

    services:
      cratedb:
        image: crate/crate:nightly
        ports:
          - 4200:4200
          - 5432:5432

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            topic/machine-learning/mlops-mlflow/requirements.txt
            topic/machine-learning/mlops-mlflow/requirements-dev.txt

      - name: Install utilities
        run: |
          pip install -r requirements.txt

      - name: Validate topic/machine-learning/mlops-mlflow
        run: |
          ngr test --accept-no-venv topic/machine-learning/mlops-mlflow
