name: C# Npgsql

on:

  # Run job only on changes to specific directories.
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/*npgsql*'
    - 'by-language/csharp-npgsql/**'
    - 'requirements.txt'
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/*npgsql*'
    - 'by-language/csharp-npgsql/**'
    - 'requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 2 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: "
     Npgsql: ${{ matrix.npgsql-version }}
     .NET: ${{ matrix.dotnet-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # , macos-latest
        dotnet-version: ['5.0.x', '6.0.x', '7.0.x']
        cratedb-version: ['nightly']
        npgsql-version: ['6.0.9', '7.0.6']

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
    services:
      cratedb:
        image: crate/crate:${{ matrix.cratedb-version }}
        ports:
          - 4200:4200
          - 5432:5432

    steps:
      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Set up .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install utilities
        run: |
          pip install -r requirements.txt

      - name: Validate by-language/csharp-npgsql, Npgsql ${{ matrix.npgsql-version }}
        run: |
          ngr test by-language/csharp-npgsql --npgsql-version=${{ matrix.npgsql-version }}

      # https://github.com/codecov/codecov-action
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: by-language-csharp-npgsql
          fail_ci_if_error: false
