name: Java jOOQ

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/test-java-jooq.yml'
    - 'by-language/java-jooq/**'
    - 'requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/test-java-jooq.yml'
    - 'by-language/java-jooq/**'
    - 'requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "
     Java: ${{ matrix.java-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        java-version: [ '11', '17' ]
        cratedb-version: [ 'nightly' ]

    services:
      cratedb:
        image: crate/crate:nightly
        ports:
          - 4200:4200
          - 5432:5432

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install utilities
        run: |
          pip install -r requirements.txt

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          cache: "gradle"

      - name: Validate by-language/java-jooq
        run: |
          ngr test by-language/java-jooq
