name: Testcontainers for Java
on:

  pull_request:
    branches: ~
    paths:
    - '.github/workflows/testcontainers-java.yml'
    - 'testing/testcontainers/java/**'
    - 'testing/ngr.py'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/testcontainers-java.yml'
    - 'testing/testcontainers/java/**'
    - 'testing/ngr.py'

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Validate testing/testcontainers/java
        run: |
          python testing/ngr.py testing/testcontainers/java
