name: Npgsql Tests

on:
  push:
    branches: [ main ]
    paths:
    - 'by-language/csharp-npgsql/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'by-language/csharp-npgsql/**'
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ".NET: ${{ matrix.dotnet-version }}
     Npgsql: ${{ matrix.npgsql-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # , macos-latest
        dotnet-version: ['3.1.x', '5.0.x']  # 6.0.0-preview.4
        cratedb-version: ['4.3.2', '4.4.3', '4.5.1', 'nightly']
        npgsql-version: ['5.0.5', '6.0.0-preview4']
      fail-fast: true

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
    services:
      cratedb:
        image: crate/crate:${{ matrix.cratedb-version }}
        ports:
          - 4200:4200
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Invoke tests on netcoreapp3.1
        if: matrix.dotnet-version == '3.1.x'
        run: |
          cd by-language/csharp-npgsql
          dotnet test --framework=netcoreapp3.1

      - name: Invoke tests on net5.0
        if: matrix.dotnet-version == '5.0.x'
        run: |
          cd by-language/csharp-npgsql
          dotnet test --framework=net5.0

      - name: Run tests with coverage
        if: matrix.dotnet-version == '5.0.x'
        run: |
          cd by-language/csharp-npgsql
          dotnet test --framework=net5.0 --collect:"XPlat Code Coverage"

      # https://github.com/codecov/codecov-action
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
