name: Testcontainers for Python

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/testing-testcontainers-python.yml'
    - 'testing/testcontainers/python**'
    - '/requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/testing-testcontainers-python.yml'
    - 'testing/testcontainers/python**'
    - '/requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "
     Python: ${{ matrix.python-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.8', '3.12' ]
        cratedb-version: [ 'nightly' ]

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            testing/testcontainers/python-pytest/requirements.txt
            testing/testcontainers/python-unittest/requirements.txt

      - name: Install utilities
        run: |
          pip install -r requirements.txt

      - name: Validate testing/testcontainers/python-{pytest,unittest}
        run: |
          ngr test --accept-no-venv testing/testcontainers/python-pytest
          ngr test --accept-no-venv testing/testcontainers/python-unittest
