name: C# Npgsql

on:

  # Run job only on changes to specific directories.
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/*npgsql*'
    - 'by-language/csharp-npgsql/**'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/*npgsql*'
    - 'by-language/csharp-npgsql/**'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 2 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash
    working-directory: by-language/csharp-npgsql

jobs:
  test:
    name: "CrateDB: ${{ matrix.cratedb-version }}
     Npgsql: ${{ matrix.npgsql-version }}
     .NET: ${{ matrix.dotnet-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # , macos-latest
        dotnet-version: ['5.0.x', '6.0.x', '7.0.x']
        cratedb-version: ['nightly']
        npgsql-version: ['6.0.9', '7.0.2']
      fail-fast: false

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
    services:
      cratedb:
        image: crate/crate:${{ matrix.cratedb-version }}
        ports:
          - 4200:4200
          - 5432:5432

    steps:
      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Set up .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Use Npgsql version ${{ matrix.npgsql-version }}
        run: |
          sed -E 's!<PackageReference Include="Npgsql" Version=".+?" />!<PackageReference Include="Npgsql" Version="${{ matrix.npgsql-version }}" />!' \
            -i demo.csproj

      - name: Display .NET information
        run: |
          dotnet --version
          dotnet --info

      - name: Display package information
        run: |
          dotnet restore
          dotnet list . package

      - name: Invoke tests on .NET 5
        if: matrix.dotnet-version == '5.0.x'
        run: |
          dotnet test --framework=net5.0 --collect:"XPlat Code Coverage"

      - name: Invoke tests on .NET 6
        if: matrix.dotnet-version == '6.0.x'
        run: |
          dotnet test --framework=net6.0 --collect:"XPlat Code Coverage"

      - name: Invoke tests on .NET 7
        if: matrix.dotnet-version == '7.0.x'
        run: |
          dotnet test --framework=net7.0 --collect:"XPlat Code Coverage"

      # https://github.com/codecov/codecov-action
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: by-language-csharp-npgsql
          fail_ci_if_error: false
