name: PHP AMPHP
on:

  pull_request:
    branches: ~
    paths:
    - '.github/workflows/test-php-amphp.yml'
    - 'by-language/php-amphp/**'
    - 'requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/test-php-amphp.yml'
    - 'by-language/php-amphp/**'
    - 'requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "CrateDB: ${{ matrix.cratedb-version }}
     PHP: ${{ matrix.php-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        cratedb-version: [ "nightly" ]
        php-version: [ "7.4", "8.2" ]

    services:
      cratedb:
        image: crate/crate:nightly
        ports:
          - 4200:4200
          - 5432:5432

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install utilities
        run: |
          pip install -r requirements.txt

      # https://github.com/marketplace/actions/setup-php-action
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Validate by-language/php-amphp
        run: |
          ngr test by-language/php-amphp
